// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftLiteTest.Data;

namespace SoftLiteTest.Migrations
{
    [DbContext(typeof(ApplicatioDbContext))]
    [Migration("20240209105355_TestDb")]
    partial class TestDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("SoftLiteTest.Models.Status", b =>
                {
                    b.Property<int>("Status_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status_Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Status_ID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Status_ID = 1,
                            Status_Name = "Создана"
                        },
                        new
                        {
                            Status_ID = 2,
                            Status_Name = "В работе"
                        },
                        new
                        {
                            Status_ID = 3,
                            Status_Name = "Создана"
                        });
                });

            modelBuilder.Entity("SoftLiteTest.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status_ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SoftLiteTest.Models.Task", b =>
                {
                    b.HasOne("SoftLiteTest.Models.Status", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("Status_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
